server:
  port: 8765

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: patient-service-route
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka