server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/new_test_micro1
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  #    drop-first: false
  #    contexts: dev
  #    default-schema: public
  cloud:
    config:
      import-check:
        enabled: false

#logging:
#  level:
#    liquibase: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    config:
      import-check:
        enabled: false