server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/new_test_micro1
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/